adapters:
  - id: usnws
    stations:
      - KGAI
capabilities:
  - id: home
  - id: controlBrowser
controls:
  - id: basement-entry-light
    name: Basement Entry Light
    type: switch
    memberships:
      - path: [category, Lighting]
      - path: [location, Main Floor, Living Room]
      - path: [location, Basement, Main Room]
    connections:
      powerOnOff: [insteon, 27d35f]
      brightness: [insteon, 27d35f]
  - id: living-room-media
    name: Living Room Media
    type: media
    memberships:
      - path: [category, Entertainment]
      - path: [location, Main Floor, Living Room]
    connections:
      powerOnOff: [harmony, hub]
      mediaSource: [harmony, hub]
  - id: thermostat
    name: Thermostat
    type: thermostat
    memberships:
      - path: [category, Climate]
    parameters:
      temperatureUnits: f
    connections:
      temperatureSetPoint: [nest, 02AA01AC021401UM]
  - id: weather
    name: Weather
    type: climateSensor
    memberships:
      - path: [category, Climate]
    parameters:
      temperatureUnits: f
    connections:
      temperatureSensor: [usnws, KGAI]
      humiditySensor: [usnws, KGAI]
  - id: living-room-climate
    name: Living Room Climate
    type: climateSensor
    memberships:
      - path: [category, Climate]
      - path: [location, Main Floor, Living Room]
    parameters:
      temperatureUnits: f
    connections:
      temperatureSensor: [nest, 02AA01AC021401UM]
      humiditySensor: [nest, 02AA01AC021401UM]
webServer:
  port: 3000
