_ = require('underscore')
Q = require('q')
Adapter = require('../../Adapter')
LGTVNode = require('./LGTVNode')

module.exports = class RadioRA3Adapter extends Adapter
  name: 'LG TV'

  # Required for each tv:
  # - ip: IP address of TV
  # - keycode: A pre-shared key generated by the TV
  # - mac: The MAC address of the TV
  defaults:
    tvs: {}

  initialize: ->
    super
    @setValid false

  start: ->
    for id, details of @get('tvs')
      @log 'verbose', "Building TV node #{id}"
      attrs = Object.assign({id: id}, details)
      @children.add new LGTVNode(attrs, {adapter: this})
